"""
Configuration system extension for multi-task support.
Extends YACS configuration with multi-task learning capabilities.
"""

from yacs.config import CfgNode as CN
import torch
import torch.nn as nn
from typing import Dict, List, Optional, Tuple, Union, Any
import logging

logger = logging.getLogger(__name__)


def add_multitask_config(cfg: CN) -> CN:
    """
    Add multi-task learning configuration to YACS CN.

    Args:
        cfg: YACS configuration node to extend

    Returns:
        Extended configuration node with multi-task settings
    """
    # Multi-task training strategies
    cfg.TRAINING_STRATEGIES = CN()
    cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK = CN()
    cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK.WEIGHTING = ""
    cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK.WEIGHTING.UNCERTAINTY = 0.0
    cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK.WEIGHTING.GRADIENT = 0.0
    cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK.WEIGHTING.PRIORITY = 0.0
    cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK.GRAD_CLIP = 0.0
    cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK.LOG_INTERVAL = 0
    cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK.EVAL_INTERVAL = 0
    cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK.SAVE_CHECKPOINT_INTERVAL = 0
    cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK.NUM_EPOCHS = 0
    cfg.TRAINING_STRATEGIES.CURRICULUM_LEARNING = CN()
    cfg.TRAINING_STRATEGIES.CURRICULUM_LEARNING.WEIGHTING = ""
    cfg.TRAINING_STRATEGIES.CURRICULUM_LEARNING.WEIGHTING.UNCERTAINTY = 0.0
    cfg.TRAINING_STRATEGIES.CURRICULUM_LEARNING.WEIGHTING.GRADIENT = 0.0
    cfg.TRAINING_STRATEGIES.CURRICULUM_LEARNING.WEIGHTING.PRIORITY = 0.0
    cfg.TRAINING_STRATEGIES.CURRICULUM_LEARNING.GRAD_CLIP = 0.0
    cfg.TRAINING_STRATEGIES.CURRICULUM_LEARNING.LOG_INTERVAL = 0
    cfg.TRAINING_STRATEGIES.CURRICULUM_LEARNING.EVAL_INTERVAL = 0
    cfg.TRAINING_STRATEGIES.CURRICULUM_LEARNING.SAVE_CHECKPOINT_INTERVAL = 0
    cfg.TRAINING_STRATEGIES.CURRICULUM_LEARNING.NUM_EPOCHS = 0
    # Multi-task data loading
    cfg.DATALOADER = CN()
    cfg.DATALOADER.SAMPLER = ""
    cfg.DATALOADER.SAMPLER.TYPE = ""
    cfg.DATALOADER.SAMPLER.TASK_WEIGHTS = None
    cfg.DATALOADER.SAMPLER.NUM_WORKERS = 0
    cfg.DATALOADER.SAMPLER.PIN_MEMORY = False
    cfg.DATALOADER.SAMPLER.SHUFFLE = True
    cfg.DATALOADER.SAMPLER.DROP_LAST = False
    cfg.DATALOADER.SAMPLER.TIMEOUT = 0
    cfg.DATALOADER.WORKER_INIT_FN = None
    cfg.DATALOADER.MULTIPROCESSING_CONTEXT = None
    cfg.DATALOADER.GENERATOR = None
    cfg.DATALOADER.PREFETCH_FACTOR = None
    cfg.DATALOADER.PERSISTENT_WORKERS = False
    cfg.DATALOADER.CURRICULUM_INFO = None
    # Multi-task evaluation framework
    cfg.EVALUATION_FRAMEWORK = CN()
    cfg.EVALUATION_FRAMEWORK.TASKS = []
    cfg.EVALUATION_FRAMEWORK.METRIC_FUNCTIONS = None
    cfg.EVALUATION_FRAMEWORK.CONSISTENCY_METRICS = True
    cfg.EVALUATION_FRAMEWORK.CROSS_TASK_CHECKS = True
    # Multi-task loss design
    cfg.LOSS_DESIGN = CN()
    cfg.LOSS_DESIGN.UNCERTAINTY_WEIGHTING = CN()
    cfg.LOSS_DESIGN.UNCERTAINTY_WEIGHTING.INIT_LOG_VAR = 0.0
    cfg.LOSS_DESIGN.UNCERTAINTY_WEIGHTING.LOG_VAR_RANGE = [-10.0, 10.0]
    cfg.LOSS_DESIGN.GRADIENT_NORMALIZATION = CN()
    cfg.LOSS_DESIGN.GRADIENT_NORMALIZATION.EPS = 0.0
    cfg.LOSS_DESIGN.TASK_PRIORITIZATION = CN()
    cfg.LOSS_DESIGN.TASK_PRIORITIZATION.PRIORITY_TYPE = ""
    cfg.LOSS_DESIGN.TASK_PRIORITIZATION.PRIORITY_TYPE.LINEAR = 0.0
    cfg.LOSS_DESIGN.TASK_PRIORITIZATION.PRIORITY_TYPE.EXPONENTIAL = 0.0
    cfg.LOSS_DESIGN.TASK_PRIORITIZATION.PRIORITY_TYPE.COSINE = 0.0
    cfg.LOSS_DESIGN.UNCERTAINTY_WEIGHTED_LOSS = CN()
    cfg.LOSS_DESIGN.UNCERTAINTY_WEIGHTED_LOSS.REDUCTION = ""
    cfg.LOSS_DESIGN.UNCERTAINTY_WEIGHTED_LOSS.REDUCTION.MEAN = 0.0
    cfg.LOSS_DESIGN.UNCERTAINTY_WEIGHTED_LOSS.REDUCTION.SUM = 0.0
    # Multi-task model configurations
    cfg.MODEL = CN()
    cfg.MODEL.BACKBONE = CN()
    cfg.MODEL.BACKBONE.SUB_MODULE = ""
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER = ""
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.NUM_LAYERS = 0
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.NUM_CHANNELS = 0
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.OUT_FEATURES = ""
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.OUT_FEATURES.F0 = 0.0
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.OUT_FEATURES.SP = 0.0
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.OUT_FEATURES.AP = 0.0
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.USE_PERIODICITY = False
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.USE_TASK_EMBEDDING = False
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.DIM_SHARED = 0
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.DIM_TASK_SHARED = 0
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.DIM_TASK_SPECIFIC = 0.0
    cfg.MODEL.BACKBONE.SUB_MODULE.SHARED_ENCODER.DEC_RATIO = 0.0
    # Multi-task shared encoder
    cfg.MULTITASK_SHARED_ENCODER = CN()
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER = ""
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.TRANSFORMER = False
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.CNN = False
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.NUM_LAYERS = 0
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.SHARED_DIM = 0
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.NUM_LAYERS = 0
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.TASK_HEADS = ""
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.TASK_HEADS.SINGING = ""
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.TASK_HEADS.SPEECH = ""
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.TASK_HEADS.NOISE_ROBUSTNESS = ""
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.TASK_HEADS.NUM_LAYERS = 0
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.FEATURE_DIM = 0
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.USE_TEMPORAL_CONTEXT = False
    cfg.MULTITASK_SHARED_ENCODER.BASE_ENCODER.CONTEXT_WINDOW = 0
    # Multi-task task heads
    cfg.TASK_HEADS = CN()
    cfg.TASK_HEADS.SINGING = ""
    cfg.TASK_HEADS.SINGING.SHARED_DIM = 0
    cfg.TASK_HEADS.SINGING.HIDDEN_DIM = 0
    cfg.TASK_HEADS.SINGING.NUM_LAYERS = 0
    cfg.TASK_HEADS.SINGING.DROPOUT = 0.0
    cfg.TASK_HEADS.SINGING.PREDICT_F0 = False
    cfg.TASK_HEADS.SINGING.PREDICT_SP = False
    cfg.TASK_HEADS.SINGING.PREDICT_AP = False
    cfg.TASK_HEADS.SINGING.SP_DIM = 0
    cfg.TASK_HEADS.SINGING.USE_PERIODICITY = False
    cfg.TASK_HEADS.SPEECH = ""
    cfg.TASK_HEADS.SPEECH.SHARED_DIM = 0
    cfg.TASK_HEADS.SPEECH.HIDDEN_DIM = 0
    cfg.TASK_HEADS.SPEECH.NUM_LAYERS = 0
    cfg.TASK_HEADS.SPEECH.DROPOUT = 0.0
    cfg.TASK_HEADS.SPEECH.PREDICT_F0 = False
    cfg.TASK_HEADS.SPEECH.PREDICT_SP = False
    cfg.TASK_HEADS.SPEECH.PREDICT_AP = False
    cfg.TASK_HEADS.SPEECH.SP_DIM = 0
    cfg.TASK_HEADS.SPEECH.USE_SPEAKER_EMBEDDING = False
    cfg.TASK_HEADS.SPEECH.SPEAKER_EMBED_DIM = 0
    cfg.TASK_HEADS.NOISE_ROBUSTNESS = ""
    cfg.TASK_HEADS.NOISE_ROBUSTNESS.SHARED_DIM = 0
    cfg.TASK_HEADS.NOISE_ROBUSTNESS.HIDDEN_DIM = 0
    cfg.TASK_HEADS.NOISE_ROBUSTNESS.NUM_LAYERS = 0
    cfg.TASK_HEADS.NOISE_ROBUSTNESS.DROPOUT = 0.0
    cfg.TASK_HEADS.NOISE_ROBUSTNESS.PREDICT_MASK = False
    cfg.TASK_HEADS.NOISE_ROBUSTNESS.PREDICT_CLEAN_FEATURES = False
    cfg.TASK_HEADS.NOISE_ROBERTNESS.PREDICT_SNR = False
    cfg.TASK_HEADS.NOISE_ROBERTNESS.FEATURE_DIM = 0
    cfg.TASK_HEADS.NOISE_ROBERTNESS.USE_TEMPORAL_CONTEXT = False
    cfg.TASK_HEADS.NOISE_ROBERTNESS.CONTEXT_WINDOW = 0
    # Configuration system extension
    cfg.SYSTEM = CN()
    cfg.SYSTEM.VERSION = 0
    cfg.SYSTEM.VERSION_MAJOR = 0
    cfg.SYSTEM.VERSION_MINOR = 0
    cfg.SYSTEM.VERSION_PATCH = 0
    cfg.SYSTEM.VERSION_TWEAK = 0

    logger.info(f"Added multi-task configuration to YACS CN")

    return cfg


def get_multitask_defaults() -> CN:
    """
    Get default multi-task configuration.

    Returns:
        Default configuration node with multi-task settings
    """
    cfg = CN("MULTITASK_DEFAULTS")
    add_multitask_config(cfg)

    logger.info("Created default multi-task configuration")

    return cfg


if __name__ == "__main__":
    # Simple test
    # Test configuration extension
    print("\nTesting configuration system extension:")
    cfg = get_multitask_defaults()

    print(f"Training strategies keys: {list(cfg.TRAINING_STRATEGIES.keys())}")
    print(f"Progressive multi-task keys: {list(cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK.keys())}")
    print(f"Weighting keys: {list(cfg.TRAINING_STRATEGIES.PROGRESSIVE_MULTI_TASK.WEIGHTING.keys())}")
    print(f"Curriculum learning keys: {list(cfg.TRAINING_STRATEGIES.CURRICULUM_LEARNING.keys())}")
    print(f"Dataloader keys: {list(cfg.DATALOADER.keys())}")
    print(f"Evaluation framework keys: {list(cfg.EVALUATION_FRAMEWORK.keys())}")
    print(f"Loss design keys: {list(cfg.LOSS_DESIGN.keys())}")
    print(f"Model keys: {list(cfg.MODEL.keys())}")
    print(f"Shared encoder keys: {list(cfg.MULTITASK_SHARED_ENCODER.keys())}")
    print(f"Task heads keys: {list(cfg.TASK_HEADS.keys())}")
    print(f"System keys: {list(cfg.SYSTEM.keys())}")

    print("\nConfiguration system extension test passed!")